### PR TITLE
Unipolar/bipolar converters

### PR DESCRIPTION
**Pull request by semrekkers**
Unary functions to convert unipolar to bipolar and vice versa. Unit tests included.

### CODE REVIEW

**Comment by brettbuddin** [comment]
A unit called `unit/adjust` is currently provided for this task. I've gone down the path of having dedicated units for these tasks, but I realized their utility is limited since you're usually not just wanting the full -1..1 or 0..1 swing in the signal. I eventually place something like `unit/adjust` after it anyway to push the signal into the range I really need for my modulation. In addition to a simple unipolar/bipolar conversion it can also function as an offset generator like you'd find in the [A-183-2](http://www.doepfer.de/a1832.htm).

Here's what I typically use for the same case:

```lisp
(-> adjust (table :in (<- bipolar-signal) :gain 0.5 :offset 0.5)) ; bipolar to unipolar
(-> adjust (table :in (<- unipolar-signal) :gain 2 :offset -1)) ; unipolar to bipolar
```

What do you think? Do you still think these units should still be included?

**Comment by semrekkers** [comment]
You're right, but the outputs are not the same. When I do this:
```
(-> unipolar (table :x (<- low-gen :sine)))
```
Compared to this:
```
(-> adjust (table :in (<- low-gen :sine) :gain 0.5 :offset 1))
```
The output of `unipolar` is in range [0, 1] and the output of `adjust` is in range [0.5, 1.5]. So then you need two units to convert bipolar to unipolar right?

**Comment by brettbuddin** [comment]
On second thought, let's just bring these in. While their usefulness is a bit more limited, I still think they are useful.

**Comment by brettbuddin** [comment]
Could you resolve the few conflicts that are there after my test-fest this weekend? 😄

**Pull request merged**
